[
    {
        tracks: 1,
        elevation: "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "RB",
        fareZone: 2,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 4105000,
        rank: 15
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "LD",
        fareZone: 2,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 1663000,
        rank: 33
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "AB",
        fareZone: 2,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 1608000,
        rank: 35,
        "yvrcheckin": "Yes"
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: 1512,
        bicycleFacilities: 45,
        disabledAccess: "Yes",
        stationCode: "BR",
        fareZone: 2,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 3938000,
        rank: 17
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "MD",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 3754000,
        rank: 18
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "LG",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 2687000,
        rank: 24
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "OK",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 2836000,
        rank: 23
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: 26,
        disabledAccess: "Yes",
        stationCode: "KE",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 2367000,
        rank: 26
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "BC",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 4748000,
        rank: 11,
        "yvrcheckin": "Yes"
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "OV",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 1710000,
        rank: 32
    },
    {
        tracks: 2,
        elevation: "Subway",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "YT",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 3722000,
        rank: 19
    },
    {
        tracks: 2,
        elevation: "Yes",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "VC",
        fareZone: 1,
        opened: "2009-08-17T07:00:00.000Z",
        perAnnumVolume: 6258000,
        rank: 6,
        "yvrcheckin": "Yes"
    },
    {
        tracks: 6,
        elevation: "At-grade and underground",
        parking: "Yes",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "WF",
        fareZone: 1,
        opened: "1914-08-01T08:00:00.000Z",
        perAnnumVolume: 13271000,
        rank: 1
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "VC",
        fareZone: 1,
        opened: "2006-01-06T08:00:00.000Z",
        perAnnumVolume: 1059000,
        rank: 44
    },
    {
        tracks: 4,
        elevation: "Below-grade and elevated\n",
        parking: "No",
        bicycleFacilities: 42,
        disabledAccess: "Yes",
        stationCode: "CM",
        fareZone: 1,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 8103000,
        rank: 3
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "RE",
        fareZone: 1,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 1352000,
        rank: 40
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "RU",
        fareZone: 1,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 975000,
        rank: 47
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "GM",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 1239000,
        rank: 43
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "BR",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 1792000,
        rank: 31
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "HO",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 1047000,
        rank: 45
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "SP",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 666000,
        rank: 51
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "LC",
        fareZone: 2,
        opened: "2003-11-21T08:00:00.000Z",
        perAnnumVolume: 384000,
        rank: 52
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: 220,
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "PW",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 1861000,
        rank: 30
    },
    {
        tracks: 3,
        elevation: "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "LH",
        fareZone: 2,
        opened: "2002-08-31T07:00:00.000Z",
        perAnnumVolume: 4144000,
        rank: 14
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "Yes",
        bicycleFacilities: 45,
        disabledAccess: "Yes",
        stationCode: "BQ",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 1441000,
        rank: 38
    },
    {
        tracks: 2,
        elevation: "At-grade and underground",
        parking: 393,
        bicycleFacilities: "No",
        disabledAccess: "Yes",
        stationCode: "MC",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 805000,
        rank: 49
    },
    {
        tracks: 2,
        elevation: "Below grade, enclosed",
        parking: "No",
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "IC",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 694200,
        rank: 50
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: 1129,
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "CC",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 1540000,
        rank: 37
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: 109,
        bicycleFacilities: "Yes",
        disabledAccess: "Yes",
        stationCode: "LN",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 1395000,
        rank: 39
    },
    {
        tracks: 2,
        elevation: "Elevated",
        parking: "No",
        bicycleFacilities: 45,
        disabledAccess: "Yes",
        stationCode: "LL",
        fareZone: 3,
        opened: "2016-12-02T08:00:00.000Z",
        perAnnumVolume: 935200,
        rank: 48
    }
]