[
    {
        "tracks": 1,
        "elevation": "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "RB",
        "farezone": 2,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 4105000,
        "rank": 15
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "LD",
        "farezone": 2,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 1663000,
        "rank": 33
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "AB",
        "farezone": 2,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 1608000,
        "rank": 35,
        "yvrcheckin": "Yes"
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: 1512,
        bicycleFacilities: 45,
        "disabledaccess": "Yes",
        "stationcode": "BR",
        "farezone": 2,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 3938000,
        "rank": 17
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "MD",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 3754000,
        "rank": 18
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "LG",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 2687000,
        "rank": 24
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "OK",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 2836000,
        "rank": 23
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: 26,
        "disabledaccess": "Yes",
        "stationcode": "KE",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 2367000,
        "rank": 26
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "BC",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 4748000,
        "rank": 11,
        "yvrcheckin": "Yes"
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "OV",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 1710000,
        "rank": 32
    },
    {
        "tracks": 2,
        "elevation": "Subway",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "YT",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 3722000,
        "rank": 19
    },
    {
        "tracks": 2,
        "elevation": "Yes",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "VC",
        "farezone": 1,
        "opened": "2009-08-17T07:00:00.000Z",
        "perannumvolume": 6258000,
        "rank": 6,
        "yvrcheckin": "Yes"
    },
    {
        "tracks": 6,
        "elevation": "At-grade and underground",
        parking: "Yes",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "WF",
        "farezone": 1,
        "opened": "1914-08-01T08:00:00.000Z",
        "perannumvolume": 13271000,
        "rank": 1
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "VC",
        "farezone": 1,
        "opened": "2006-01-06T08:00:00.000Z",
        "perannumvolume": 1059000,
        "rank": 44
    },
    {
        "tracks": 4,
        "elevation": "Below-grade and elevated\n",
        parking: "No",
        bicycleFacilities: 42,
        "disabledaccess": "Yes",
        "stationcode": "CM",
        "farezone": 1,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 8103000,
        "rank": 3
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "RE",
        "farezone": 1,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 1352000,
        "rank": 40
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "RU",
        "farezone": 1,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 975000,
        "rank": 47
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "GM",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 1239000,
        "rank": 43
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "BR",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 1792000,
        "rank": 31
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "HO",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 1047000,
        "rank": 45
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "SP",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 666000,
        "rank": 51
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "LC",
        "farezone": 2,
        "opened": "2003-11-21T08:00:00.000Z",
        "perannumvolume": 384000,
        "rank": 52
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: 220,
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "PW",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 1861000,
        "rank": 30
    },
    {
        "tracks": 3,
        "elevation": "Elevated",
        parking: "Yes",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "LH",
        "farezone": 2,
        "opened": "2002-08-31T07:00:00.000Z",
        "perannumvolume": 4144000,
        "rank": 14
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "Yes",
        bicycleFacilities: 45,
        "disabledaccess": "Yes",
        "stationcode": "BQ",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 1441000,
        "rank": 38
    },
    {
        "tracks": 2,
        "elevation": "At-grade and underground",
        parking: 393,
        bicycleFacilities: "No",
        "disabledaccess": "Yes",
        "stationcode": "MC",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 805000,
        "rank": 49
    },
    {
        "tracks": 2,
        "elevation": "Below grade, enclosed",
        parking: "No",
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "IC",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 694200,
        "rank": 50
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: 1129,
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "CC",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 1540000,
        "rank": 37
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: 109,
        bicycleFacilities: "Yes",
        "disabledaccess": "Yes",
        "stationcode": "LN",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 1395000,
        "rank": 39
    },
    {
        "tracks": 2,
        "elevation": "Elevated",
        parking: "No",
        bicycleFacilities: 45,
        "disabledaccess": "Yes",
        "stationcode": "LL",
        "farezone": 3,
        "opened": "2016-12-02T08:00:00.000Z",
        "perannumvolume": 935200,
        "rank": 48
    }
]